comm:
  command_port: 9001
  data_port: 9002
  device_baud: 9600
  device_data_bits: 8
  device_flow_control: 0
  device_os_port: /dev/ttymi01
  device_parity: 0
  device_stop_bits: 1
  method: serial
