# DEFAULT LOGGING CONFIGURATION FOR MARINE INTEGRATION PROJECT
#
# NOTE: this file may not be used!
#       this file is a backup packaged with marine-integrations
#       only in the case res/config/mi-logging.yml is not found.
#       this guarantees the logging will not be completely disabled if the environment is not configured properly.
#
# NOTE: this configuration writes logfiles in the current working directory!
#       if we are using this file at all, we don't know how the environment has been configured and
#       don't want to assume there is a log/ subdirectory.

### BOILERPLATE -- do not alter
#
version: 1
formatters:
  brief:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(threadName)s %(name)-15s:%(lineno)d %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    level: DEBUG
    ### end of BOILERPLATE -- change logfile location and size below:
    filename: mi-drivers.log
    maxBytes: 1024000
    backupCount: 3

### change log levels below:
loggers:
  pyon:
    handlers: [console, file]
    level: WARNING

  prototype:
    handlers: [console]
    level: WARNING

  ion:
    handlers: [console, file]
    level: WARNING

  examples:
    handlers: [console, file]
    level: WARNING

  prototype:
    handlers: [console, file]
    level: WARNING

  mi:
    handlers: [console, file]
    level: INFO

#  mi.example.module:
#    level: DEBUG